# Generated by Django 2.2.16 on 2022-04-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220420_1838'),
        ('reviews', '0003_auto_20220420_1722'),
    ]

    operations = [
    ]
