# Generated by Django 2.2.16 on 2022-04-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220413_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title_id',
            new_name='title',
        ),
    ]
